# **El poder viral**: historias en la era digital

In [2]:
import pandas as pd
import numpy as np
import functions as f
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
## Importamos datos 
df = pd.read_csv('data/OnlineNewsPopularity.csv')

In [4]:
df.head()

,url,timedelta,n_tokens_title,n_tokens_content,n_unique_tokens,n_non_stop_words,n_non_stop_unique_tokens,num_hrefs,num_self_hrefs,num_imgs,...,min_positive_polarity,max_positive_polarity,avg_negative_polarity,min_negative_polarity,max_negative_polarity,title_subjectivity,title_sentiment_polarity,abs_title_subjectivity,abs_title_sentiment_polarity,shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,...,0.100000,0.7,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.0,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,...,0.033333,0.7,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.0,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,...,0.100000,1.0,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.0,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,...,0.136364,0.8,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.0,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,...,0.033333,1.0,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505

In [5]:
## Hacemos exploración previa 
f.explorar_df(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39644 entries, 0 to 39643
Data columns (total 61 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   url                             39644 non-null  object
 1    timedelta                      39644 non-null  float64
 2    n_tokens_title                 39644 non-null  float64
 3    n_tokens_content               39644 non-null  float64
 4    n_unique_tokens                39644 non-null  float64
 5    n_non_stop_words               39644 non-null  float64
 6    n_non_stop_unique_tokens       39644 non-null  float64
 7    num_hrefs                      39644 non-null  float64
 8    num_self_hrefs                 39644 non-null  float64
 9    num_imgs                       39644 non-null  float64
 10   num_videos                     39644 non-null  float64
 11   average_token_length           39644 non-null  float64
 12   num_keywords                   39644 non-null  float64
 13   data_channel_is_lifestyle      39644 non-null  float64
 14   data_channel_is_entertainment  39644 non-null  float64
 15   data_channel_is_bus            39644 non-null  float64
 16   data_channel_is_socmed         39644 non-null  float64
 17   data_channel_is_tech           39644 non-null  float64
 18   data_channel_is_world          39644 non-null  float64
 19   kw_min_min                     39644 non-null  float64
 20   kw_max_min                     39644 non-null  float64
 21   kw_avg_min                     39644 non-null  float64
 22   kw_min_max                     39644 non-null  float64
 23   kw_max_max                     39644 non-null  float64
 24   kw_avg_max                     39644 non-null  float64
 25   kw_min_avg                     39644 non-null  float64
 26   kw_max_avg                     39644 non-null  float64
 27   kw_avg_avg                     39644 non-null  float64
 28   self_reference_min_shares      39644 non-null  float64
 29   self_reference_max_shares      39644 non-null  float64
 30   self_reference_avg_sharess     39644 non-null  float64
 31   weekday_is_monday              39644 non-null  float64
 32   weekday_is_tuesday             39644 non-null  float64
 33   weekday_is_wednesday           39644 non-null  float64
 34   weekday_is_thursday            39644 non-null  float64
 35   weekday_is_friday              39644 non-null  float64
 36   weekday_is_saturday            39644 non-null  float64
 37   weekday_is_sunday              39644 non-null  float64
 38   is_weekend                     39644 non-null  float64
 39   LDA_00                         39644 non-null  float64
 40   LDA_01                         39644 non-null  float64
 41   LDA_02                         39644 non-null  float64
 42   LDA_03                         39644 non-null  float64
 43   LDA_04                         39644 non-null  float64
 44   global_subjectivity            39644 non-null  float64
 45   global_sentiment_polarity      39644 non-null  float64
 46   global_rate_positive_words     39644 non-null  float64
 47   global_rate_negative_words     39644 non-null  float64
 48   rate_positive_words            39644 non-null  float64
 49   rate_negative_words            39644 non-null  float64
 50   avg_positive_polarity          39644 non-null  float64
 51   min_positive_polarity          39644 non-null  float64
 52   max_positive_polarity          39644 non-null  float64
 53   avg_negative_polarity          39644 non-null  float64
 54   min_negative_polarity          39644 non-null  float64
 55   max_negative_polarity          39644 non-null  float64
 56   title_subjectivity             39644 non-null  float64
 57   title_sentiment_polarity       39644 non-null  float64
 58   abs_title_subjectivity         39644 non-null  float64
 59   abs_title_sentiment_polarity   39644 non-null  float64
 60   shares                         39644 non-null  int64
dtypes: float64(59), int64(1), object(1)
memory usage: 18.5+ MB
None
Primeras filas
                                                 url   timedelta  \
0  http://mashable.com/2013/01/07/amazon-instant-...       731.0
1  http://mashable.com/2013/01/07/ap-samsung-spon...       731.0
2  http://mashable.com/2013/01/07/apple-40-billio...       731.0
3  http://mashable.com/2013/01/07/astronaut-notre...       731.0
4   http://mashable.com/2013/01/07/att-u-verse-apps/       731.0

    n_tokens_title   n_tokens_content   n_unique_tokens   n_non_stop_words  \
0             12.0              219.0          0.663594                1.0
1              9.0              255.0          0.604743                1.0
2              9.0              211.0          0.575130                1.0
3              9.0              531.0          0.503788                1.0
4             13.0             1072.0          0.415646                1.0

    n_non_stop_unique_tokens   num_hrefs   num_self_hrefs   num_imgs  ...  \
0                   0.815385         4.0              2.0        1.0  ...
1                   0.791946         3.0              1.0        1.0  ...
2                   0.663866         3.0              1.0        1.0  ...
3                   0.665635         9.0              0.0        1.0  ...
4                   0.540890        19.0             19.0       20.0  ...

    min_positive_polarity   max_positive_polarity   avg_negative_polarity  \
0                0.100000                     0.7               -0.350000
1                0.033333                     0.7               -0.118750
2                0.100000                     1.0               -0.466667
3                0.136364                     0.8               -0.369697
4                0.033333                     1.0               -0.220192

    min_negative_polarity   max_negative_polarity   title_subjectivity  \
0                  -0.600               -0.200000             0.500000
1                  -0.125               -0.100000             0.000000
2                  -0.800               -0.133333             0.000000
3                  -0.600               -0.166667             0.000000
4                  -0.500               -0.050000             0.454545

    title_sentiment_polarity   abs_title_subjectivity  \
0                  -0.187500                 0.000000
1                   0.000000                 0.500000
2                   0.000000                 0.500000
3                   0.000000                 0.500000
4                   0.136364                 0.045455

    abs_title_sentiment_polarity   shares
0                       0.187500      593
1                       0.000000      711
2                       0.000000     1500
3                       0.000000     1200
4                       0.136364      505

[5 rows x 61 columns]
Describe()
                                 count unique  \
url                              39644  39644
 timedelta                     39644.0    NaN
 n_tokens_title                39644.0    NaN
 n_tokens_content              39644.0    NaN
 n_unique_tokens               39644.0    NaN
...                                ...    ...
 title_subjectivity            39644.0    NaN
 title_sentiment_polarity      39644.0    NaN
 abs_title_subjectivity        39644.0    NaN
 abs_title_sentiment_polarity  39644.0    NaN
 shares                        39644.0    NaN

                                                                             top  \
url                            http://mashable.com/2013/01/07/amazon-instant-...
 timedelta                                                                   NaN
 n_tokens_title                                                              NaN
 n_tokens_content                                                            NaN
 n_unique_tokens                                                             NaN
...                                                                          ...
 title_subjectivity                                                          NaN
 title_sentiment_polarity                                                    NaN
 abs_title_subjectivity                                                      NaN
 abs_title_sentiment_polarity                                                NaN
 shares                                                                      NaN

                              freq         mean           std  min       25%  \
url                              1          NaN           NaN  NaN       NaN
 timedelta                     NaN   354.530471    214.163767  8.0     164.0
 n_tokens_title                NaN    10.398749      2.114037  2.0       9.0
 n_tokens_content              NaN   546.514731    471.107508  0.0     246.0
 n_unique_tokens               NaN     0.548216      3.520708  0.0   0.47087
...                            ...          ...           ...  ...       ...
 title_subjectivity            NaN     0.282353      0.324247  0.0       0.0
 title_sentiment_polarity      NaN     0.071425       0.26545 -1.0       0.0
 abs_title_subjectivity        NaN     0.341843      0.188791  0.0  0.166667
 abs_title_sentiment_polarity  NaN     0.156064      0.226294  0.0       0.0
 shares                        NaN  3395.380184  11626.950749  1.0     946.0

                                    50%       75%       max
url                                 NaN       NaN       NaN
 timedelta                        339.0     542.0     731.0
 n_tokens_title                    10.0      12.0      23.0
 n_tokens_content                 409.0     716.0    8474.0
 n_unique_tokens               0.539226  0.608696     701.0
...                                 ...       ...       ...
 title_subjectivity                0.15       0.5       1.0
 title_sentiment_polarity           0.0      0.15       1.0
 abs_title_subjectivity             0.5       0.5       0.5
 abs_title_sentiment_polarity       0.0      0.25       1.0
 shares                          1400.0    2800.0  843300.0

[61 rows x 11 columns]
Nulos
Notnnull
Duplicados
0
Tamaño
Filas: 39644 | Columnas: 61

In [6]:
## Aunque no parece haber nulos o duplicados, vamos a aplicar la función de limpieza para asegurarnos de que el dataset está listo para el análisis y unificado.
f.limpiar_dataset(df)

,url,_timedelta,_n_tokens_title,_n_tokens_content,_n_unique_tokens,_n_non_stop_words,_n_non_stop_unique_tokens,_num_hrefs,_num_self_hrefs,_num_imgs,...,_min_positive_polarity,_max_positive_polarity,_avg_negative_polarity,_min_negative_polarity,_max_negative_polarity,_title_subjectivity,_title_sentiment_polarity,_abs_title_subjectivity,_abs_title_sentiment_polarity,_shares
0,http://mashable.com/2013/01/07/amazon-instant-...,731.0,12.0,219.0,0.663594,1.0,0.815385,4.0,2.0,1.0,...,0.100000,0.70,-0.350000,-0.600,-0.200000,0.500000,-0.187500,0.000000,0.187500,593
1,http://mashable.com/2013/01/07/ap-samsung-spon...,731.0,9.0,255.0,0.604743,1.0,0.791946,3.0,1.0,1.0,...,0.033333,0.70,-0.118750,-0.125,-0.100000,0.000000,0.000000,0.500000,0.000000,711
2,http://mashable.com/2013/01/07/apple-40-billio...,731.0,9.0,211.0,0.575130,1.0,0.663866,3.0,1.0,1.0,...,0.100000,1.00,-0.466667,-0.800,-0.133333,0.000000,0.000000,0.500000,0.000000,1500
3,http://mashable.com/2013/01/07/astronaut-notre...,731.0,9.0,531.0,0.503788,1.0,0.665635,9.0,0.0,1.0,...,0.136364,0.80,-0.369697,-0.600,-0.166667,0.000000,0.000000,0.500000,0.000000,1200
4,http://mashable.com/2013/01/07/att-u-verse-apps/,731.0,13.0,1072.0,0.415646,1.0,0.540890,19.0,19.0,20.0,...,0.033333,1.00,-0.220192,-0.500,-0.050000,0.454545,0.136364,0.045455,0.136364,505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39639,http://mashable.com/2014/12/27/samsung-app-aut...,8.0,11.0,346.0,0.529052,1.0,0.684783,9.0,7.0,1.0,...,0.100000,0.75,-0.260000,-0.500,-0.125000,0.100000,0.000000,0.400000,0.000000,1800
39640,http://mashable.com/2014/12/27/seth-rogen-jame...,8.0,12.0,328.0,0.696296,1.0,0.885057,9.0,7.0,3.0,...,0.136364,0.70,-0.211111,-0.400,-0.100000,0.300000,1.000000,0.200000,1.000000,1900
39641,http://mashable.com/2014/12/27/son-pays-off-mo...,8.0,10.0,442.0,0.516355,1.0,0.644128,24.0,1.0,12.0,...,0.136364,0.50,-0.356439,-0.800,-0.166667,0.454545,0.136364,0.045455,0.136364,1900
39642,http://mashable.com/2014/12/27/ukraine-blasts/,8.0,6.0,682.0,0.539493,1.0,0.692661,10.0,1.0,1.0,...,0.062500,0.50,-0.205246,-0.500,-0.012500,0.000000,0.000000,0.500000,0.000000,1100
39643,http://mashable.com/2014/12/27/youtube-channel...,8.0,10.0,157.0,0.701987,1.0,0.846154,1.0,1.0,0.0,...,0.100000,0.50,-0.200000,-0.200,-0.200000,0.333333,0.250000,0.166667,0.250000,1300

In [7]:
## Eliminando el espacio antes de cada categoría 
df.columns = df.columns.str.strip()

In [8]:
## Comprobando que funciona 
df.columns

Index(['url', 'timedelta', 'n_tokens_title', 'n_tokens_content',
       'n_unique_tokens', 'n_non_stop_words', 'n_non_stop_unique_tokens',
       'num_hrefs', 'num_self_hrefs', 'num_imgs', 'num_videos',
       'average_token_length', 'num_keywords', 'data_channel_is_lifestyle',
       'data_channel_is_entertainment', 'data_channel_is_bus',
       'data_channel_is_socmed', 'data_channel_is_tech',
       'data_channel_is_world', 'kw_min_min', 'kw_max_min', 'kw_avg_min',
       'kw_min_max', 'kw_max_max', 'kw_avg_max', 'kw_min_avg', 'kw_max_avg',
       'kw_avg_avg', 'self_reference_min_shares', 'self_reference_max_shares',
       'self_reference_avg_sharess', 'weekday_is_monday', 'weekday_is_tuesday',
       'weekday_is_wednesday', 'weekday_is_thursday', 'weekday_is_friday',
       'weekday_is_saturday', 'weekday_is_sunday', 'is_weekend', 'LDA_00',
       'LDA_01', 'LDA_02', 'LDA_03', 'LDA_04', 'global_subjectivity',
       'global_sentiment_polarity', 'global_rate_positive_words',
       'global_rate_negative_words', 'rate_positive_words',
       'rate_negative_words', 'avg_positive_polarity', 'min_positive_polarity',
       'max_positive_polarity', 'avg_negative_polarity',
       'min_negative_polarity', 'max_negative_polarity', 'title_subjectivity',
       'title_sentiment_polarity', 'abs_title_subjectivity',
       'abs_title_sentiment_polarity', 'shares'],
      dtype='object')

In [9]:
## Comprobando los tipos de datos
df.dtypes

url                              object
timedelta                       float64
n_tokens_title                  float64
n_tokens_content                float64
n_unique_tokens                 float64
                                 ...
title_subjectivity              float64
title_sentiment_polarity        float64
abs_title_subjectivity          float64
abs_title_sentiment_polarity    float64
shares                            int64
Length: 61, dtype: object

In [10]:
df.rename(columns={'timedelta': 'dias_pub_a_ext',
                   'n_tokens_title': 'num_palabras_titulo',
                   'n_tokens_content': 'num_palabras_contenido',
                   'n_unique_tokens': 'tasa_palabras_unicas',
                   'n_non_stop_words': 'tasa_palabras_no_stop',
                   'n_non_stop_unique_tokens': 'tasa_palabras_unicas_no_stop',
                   'num_hrefs': 'num_enlaces',
                   'num_self_hrefs': 'num_enlaces_propios',
                   'average_token_length': 'longitud_media_palabras',
                   'data_channel_is_lifestyle': 'lifestyle',
                   'data_channel_is_entertainment': 'entretenimiento',
                   'data_channel_is_bus': 'negocios',
                   'data_channel_is_socmed': 'redes_sociales',
                   'data_channel_is_tech': 'tecnologia',
                   'data_channel_is_world': 'noticias_globales',
                   'kw_min_min' : 'rendimiento_min_peor',
                   'kw_max_min' : 'rendimiento_max_peor',
                   'kw_avg_min' : 'rendimiento_promedio_peor',
                   'kw_min_max' : 'rendimiento_min_mejor',
                   'kw_max_max' : 'rendimiento_max_mejor',
                   'kw_avg_max' : 'rendimiento_promedio_mejor',
                   'kw_min_avg' : 'rendimiento_min_media',
                   'kw_max_avg' : 'rendimiento_max_media',
                   'kw_avg_avg' : 'rendimiento_promedio_media',
                   'weekday_is_monday': 'lunes',
                   'weekday_is_tuesday': 'martes',
                   'weekday_is_wednesday': 'miercoles',
                   'weekday_is_thursday': 'jueves',
                   'weekday_is_friday': 'viernes',
                   'weekday_is_saturday': 'sabado',
                   'weekday_is_sunday': 'domingo',
                   'is_weekend': 'fin_de_semana',
                   'global_subjectivity': 'subjetividad_global',
                   'global_sentiment_polarity': 'polaridad_global',
                   'global_rate_positive_words': 'tasa_palabras_positivas_global',
                   'global_rate_negative_words': 'tasa_palabras_negativas_global',
                   'rate_positive_words': 'tasa_palabras_positivas',
                   'rate_negative_words': 'tasa_palabras_negativas',
                   'avg_positive_polarity': 'polaridad_positiva_media',
                   'min_positive_polarity': 'polaridad_positiva_min',
                   'max_positive_polarity': 'polaridad_positiva_max',
                   'avg_negative_polarity': 'polaridad_negativa_media',
                   'min_negative_polarity': 'polaridad_negativa_min',
                   'max_negative_polarity': 'polaridad_negativa_max',
                   'title_subjectivity': 'subjetividad_titulo',
                   'title_sentiment_polarity': 'polaridad_titulo', 
                   'shares': 'num_compartidos'

                   }, inplace=True)

In [11]:
df.columns

Index(['url', 'dias_pub_a_ext', 'num_palabras_titulo',
       'num_palabras_contenido', 'tasa_palabras_unicas',
       'tasa_palabras_no_stop', 'tasa_palabras_unicas_no_stop', 'num_enlaces',
       'num_enlaces_propios', 'num_imgs', 'num_videos',
       'longitud_media_palabras', 'num_keywords', 'lifestyle',
       'entretenimiento', 'negocios', 'redes_sociales', 'tecnologia',
       'noticias_globales', 'rendimiento_min_peor', 'rendimiento_max_peor',
       'rendimiento_promedio_peor', 'rendimiento_min_mejor',
       'rendimiento_max_mejor', 'rendimiento_promedio_mejor',
       'rendimiento_min_media', 'rendimiento_max_media',
       'rendimiento_promedio_media', 'self_reference_min_shares',
       'self_reference_max_shares', 'self_reference_avg_sharess', 'lunes',
       'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo',
       'fin_de_semana', 'LDA_00', 'LDA_01', 'LDA_02', 'LDA_03', 'LDA_04',
       'subjetividad_global', 'polaridad_global',
       'tasa_palabras_positivas_global', 'tasa_palabras_negativas_global',
       'tasa_palabras_positivas', 'tasa_palabras_negativas',
       'polaridad_positiva_media', 'polaridad_positiva_min',
       'polaridad_positiva_max', 'polaridad_negativa_media',
       'polaridad_negativa_min', 'polaridad_negativa_max',
       'subjetividad_titulo', 'polaridad_titulo', 'abs_title_subjectivity',
       'abs_title_sentiment_polarity', 'num_compartidos'],
      dtype='object')

In [12]:
# Para hacer el nuevo df para el siguiente notebook 
!df.to_csv('df.csv', index=False)

zsh:1: number expected

In [13]:
df.shape

(39644, 61)

## Diccionario original de nuestro dataset 

**1. Metadatos del Artículo**

url: El enlace al artículo (se usa como identificador).

timedelta: Días transcurridos entre la publicación del artículo y la extracción de los datos.

n_tokens_title: Número de palabras en el título.

n_tokens_content: Número de palabras en el contenido del artículo.

num_keywords: Número de palabras clave asociadas al artículo.

**2. Contenido y Enlaces**

n_unique_tokens: Tasa de palabras únicas en el contenido.

n_non_stop_words: Tasa de palabras que no son "stop words" (palabras comunes como "el", "de", "y").

n_non_stop_unique_tokens: Tasa de palabras únicas que no son "stop words".

num_hrefs: Número de enlaces (hipervínculos).

num_self_hrefs: Número de enlaces que apuntan a otros artículos del mismo Mashable.

num_imgs / num_videos: Cantidad de imágenes y vídeos incluidos.

average_token_length: Longitud promedio de las palabras en el contenido.

**3. Canales de Datos (Temática)**

Estas son variables binarias (0 o 1). Indican si el artículo pertenece a una categoría específica:

data_channel_is_lifestyle: Estilo de vida.

data_channel_is_entertainment: Entretenimiento.

data_channel_is_bus: Negocios (Business).

data_channel_is_socmed: Redes Sociales.

data_channel_is_tech: Tecnología.

data_channel_is_world: Noticias mundiales.

**4. Estadísticas de Palabras Clave (Keywords)**

Miden el éxito previo de las palabras clave utilizadas en el artículo (basado en cuántas veces se compartieron otros artículos con esas mismas keywords):

kw_min_min / kw_max_min / kw_avg_min: Rendimiento mínimo/máximo/promedio de la palabra clave que peor funcionó.

kw_min_max / kw_max_max / kw_avg_max: Rendimiento mínimo/máximo/promedio de la palabra clave que mejor funcionó.

kw_min_avg / kw_max_avg / kw_avg_avg: Rendimiento mínimo/máximo/promedio de la media de las palabras clave.

**5. Día de la Semana**

Indican qué día fue publicado el artículo (binarias):

weekday_is_monday a weekday_is_sunday.

is_weekend: Indica si se publicó en sábado o domingo.

**6. NLP y Análisis de Sentimiento**

LDA_00 a LDA_04: Distribución de 5 temas extraídos mediante Latent Dirichlet Allocation (un algoritmo que agrupa artículos por temas abstractos).

global_subjectivity: Nivel de subjetividad del texto.

global_sentiment_polarity: Polaridad del sentimiento general (positivo o negativo).

global_rate_positive_words / global_rate_negative_words: Tasa de palabras positivas y negativas en el texto.

avg_positive_polarity / avg_negative_polarity: Promedio de la intensidad de las palabras positivas/negativas.

title_subjectivity / title_sentiment_polarity: Subjetividad y sentimiento aplicados específicamente al título.

**7. Variable Objetivo (Target)**

shares: El número total de veces que el artículo fue compartido en redes sociales. Esta es la métrica de éxito.